// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHvlHGpXqxMlLqMaExqR07vOrH1150uXE',
    appId: '1:81516595224:web:77b58c04524ae56b455b6d',
    messagingSenderId: '81516595224',
    projectId: 'team-hhouse',
    authDomain: 'team-hhouse.firebaseapp.com',
    storageBucket: 'team-hhouse.appspot.com',
    measurementId: 'G-04VBNLXSNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCl96TK1x7BYu8H3r-hxPfYCCZKNFbxM',
    appId: '1:81516595224:android:74b92097b5238250455b6d',
    messagingSenderId: '81516595224',
    projectId: 'team-hhouse',
    storageBucket: 'team-hhouse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzugpjG4d-adpYUwOeWitBYaA4vBXj-oo',
    appId: '1:81516595224:ios:f433b4fdc74f7fb0455b6d',
    messagingSenderId: '81516595224',
    projectId: 'team-hhouse',
    storageBucket: 'team-hhouse.appspot.com',
    iosBundleId: 'com.iycreateapp.myhostel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzugpjG4d-adpYUwOeWitBYaA4vBXj-oo',
    appId: '1:81516595224:ios:f433b4fdc74f7fb0455b6d',
    messagingSenderId: '81516595224',
    projectId: 'team-hhouse',
    storageBucket: 'team-hhouse.appspot.com',
    iosBundleId: 'com.iycreateapp.myhostel',
  );
}
