// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvcO51yajR4-an_tEvkE6aDLKz9a2tIJE',
    appId: '1:596551481280:web:28f04f62474c76e6767a25',
    messagingSenderId: '596551481280',
    projectId: 'hhouse-final',
    authDomain: 'hhouse-final.firebaseapp.com',
    storageBucket: 'hhouse-final.appspot.com',
    measurementId: 'G-3S4HEN1YF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOZJ2YIrtTx13TEGVS1Cd9XYVqWerdyV4',
    appId: '1:596551481280:android:eb0120624fb5a5a0767a25',
    messagingSenderId: '596551481280',
    projectId: 'hhouse-final',
    storageBucket: 'hhouse-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNLR6NQaCsrOSzRKGVSwelooFe74jJyg',
    appId: '1:596551481280:ios:9d87fd179eff679f767a25',
    messagingSenderId: '596551481280',
    projectId: 'hhouse-final',
    storageBucket: 'hhouse-final.appspot.com',
    iosClientId: '596551481280-5ssupfgn9r8pp746guk0on7ljp2ufpl1.apps.googleusercontent.com',
    iosBundleId: 'com.iycreateapp.myhostel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFNLR6NQaCsrOSzRKGVSwelooFe74jJyg',
    appId: '1:596551481280:ios:9d87fd179eff679f767a25',
    messagingSenderId: '596551481280',
    projectId: 'hhouse-final',
    storageBucket: 'hhouse-final.appspot.com',
    iosClientId: '596551481280-5ssupfgn9r8pp746guk0on7ljp2ufpl1.apps.googleusercontent.com',
    iosBundleId: 'com.iycreateapp.myhostel',
  );

}